### ISSUE TITLE
Error " 'list' object has no attribute 'cpu' "

### ISSUE THREAD

**Issue by MattRM2** [Loewen-Hob/rembg-comfyui-node#4]
Hi,

I would like to know how to resolve this error `'list' object has no attribute 'cpu'` ?
I  done this `git clone https://github.com/Loewen-Hob/rembg-comfyui-node-better.git` but can't found a way to do this `pip install rembg[gpu]` to my ComfyUI virtual environment.

Can you help me to do the pip intall part ? Thx

Matt

**Comment by MattRM2** [comment]
More information here on the error : 
`2024-05-28 13:29:10.5843530 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-05-28 13:29:11.1063927 [W:onnxruntime:, transformer_memcpy.cc:74 onnxruntime::MemcpyTransformer::ApplyImpl] 200 Memcpy nodes are added to the graph torch_jit for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
2024-05-28 13:29:11.3117744 [E:onnxruntime:Default, provider_bridge_ort.cc:1534 onnxruntime::TryGetProviderInfo_TensorRT] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "E:\00_ComfyUI_Fooocus\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

*************** EP Error ***************
EP Error D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:456 onnxruntime::python::RegisterTensorRTPluginsAsCustomOps Please install TensorRT libraries as mentioned in the GPU requirements page, make sure they're in the PATH or LD_LIBRARY_PATH, and that your GPU is supported.
 when using ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
Falling back to ['CUDAExecutionProvider', 'CPUExecutionProvider'] and retrying.
****************************************
2024-05-28 13:29:11.4921354 [W:onnxruntime:, transformer_memcpy.cc:74 onnxruntime::MemcpyTransformer::ApplyImpl] 143 Memcpy nodes are added to the graph torch_jit for CUDAExecutionProvider. It might have negative impact on performance (including unable to run CUDA graph). Set session_options.log_severity_level=1 to see the detail logs before this message.
!!! Exception during processing!!! 'list' object has no attribute 'cpu'
Traceback (most recent call last):
  File "E:\00_ComfyUI_Fooocus\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\00_ComfyUI_Fooocus\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\00_ComfyUI_Fooocus\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\00_ComfyUI_Fooocus\ComfyUI\custom_nodes\rembg-comfyui-node-better\__init__.py", line 38, in remove_background
    image = pil2tensor(remove(tensor2pil(image), session = session))
  File "E:\00_ComfyUI_Fooocus\ComfyUI\custom_nodes\rembg-comfyui-node-better\__init__.py", line 8, in tensor2pil
    return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
AttributeError: 'list' object has no attribute 'cpu'

Prompt executed in 145.49 seconds`

Matt

**Comment by Loewen-Hob** [comment]
Just pip install in the terminal

**Comment by MattRM2** [comment]
Hi,

I done this right now and got this message :
`DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063`

Does I need to udpate something else but without broking my current ComfyUI installation ?
I'll do a backup to be secure but what to update ?

Thx

Matt

**Comment by MattRM2** [comment]
Hi,

Solved with removing RemBG + onnxruntime and re-install it.
